src/java/JsfClass/PeriodController.java
package JsfClass;

import Entity.Period;
import Entity.Saham;
import Entity.Users;
import JsfClass.util.JsfUtil;
import JsfClass.util.JsfUtil.PersistAction;
import SessionBean.PeriodFacade;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@Named("periodController")
@SessionScoped
public class PeriodController implements Serializable {

    @EJB
    private SessionBean.PeriodFacade ejbFacade;
    @EJB
    private SessionBean.SahamFacade sahamFacade;
    private List<Period> items = null;
    private Period selected;
    private String newCount;

    public String getNewCount() {
        return newCount;
    }

    public void setNewCount(String newCount) {
        this.newCount = newCount;
    }

    public Period getBase() {
        return ejbFacade.getBase();
    }

    public Period getNow() {
        return ejbFacade.getNow();
    }

    public PeriodController() {
    }

    public Period getSelected() {
        return selected;
    }

    public void setSelected(Period selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private PeriodFacade getFacade() {
        return ejbFacade;
    }

    public Period prepareCreate() {
        selected = new Period();
        initializeEmbeddableKey();
        return selected;
    }
    private int NotEquals = 0;

    public int getNotEquals() {
        return NotEquals;
    }

    public void setNotEquals(int NotEquals) {
        this.NotEquals = NotEquals;
    }
    private int addSaham;

    public int getAddSaham() {
        return addSaham;
    }

    public void setAddSaham(int addSaham) {
        this.addSaham = addSaham;
    }

    private Users user;

    public Users getUser() {
        return user;
    }

    public void setUser(Users user) {
        this.user = user;
    }

    public void addSahamToUser() {
        System.out.println("User Is ==> " + user.getName() + " add Count is ==> " + addSaham);
        if (addSaham <= NotEquals) {
            Saham newSaham = new Saham();
            newSaham.setCount(addSaham);
            newSaham.setSerialNo(String.valueOf(Integer.valueOf(sahamFacade.getLastSerialNo().getSerialNo()) + 1));
            newSaham.setStatus(1);
            newSaham.setUserId(user);
            newSaham.setDateRegister(new Date());
            NotEquals = NotEquals - addSaham;
            sahamFacade.create(newSaham);
            this.selected = ejbFacade.getNow();
            selected.setNotEquale(NotEquals);
            JsfUtil.addSuccessMessage("این سهام افزوده شد مقدار " + NotEquals + " باقی مانده است");
            getFacade().edit(selected);
        } else {
            JsfUtil.addErrorMessage("مقدار وارد شده صحیح نمی باشد");
        }
    }
    
    public boolean checkNotEquale(){
        selected = ejbFacade.getNow();
        if(selected != null && selected.getNotEquale() != null && selected.getNotEquale() > 0){
            this.NotEquals = selected.getNotEquale();
            return true;
        }
        return false;
    }
    public void create() {
        Integer oldCount = sahamFacade.getCountActiveSaham();
        if ((ejbFacade.count() == 1 && oldCount == 45701) || ejbFacade.count() > 1) {
            if (!newCount.isEmpty()) {
                float sharesOffer = ((Float.valueOf(newCount)) / oldCount);
                String helpShare = String.valueOf(sharesOffer);
                helpShare = helpShare.length() > 4 ? helpShare.substring(0, 4) : helpShare;
                sharesOffer = Float.valueOf(helpShare);
                selected.setNewCount(Integer.valueOf(this.newCount));
                selected.setOldCount(oldCount);
                selected.setSharesOffer(sharesOffer);
                this.NotEquals = (int) (Integer.valueOf(newCount) - (oldCount * sharesOffer));
                selected.setNotEquale(NotEquals);
//                System.out.println("Old Count is : " + oldCount + " ,newCount : " + newCount + " ,ShareOffer is : " + sharesOffer + " ,shareoffer * oldCount is : " + (sharesOffer * oldCount));
            }
            if (oldCount > 1) {
                selected.setLastSerialNo(Integer.valueOf(sahamFacade.getLastSerialNo().getSerialNo()));
            }
            if (selected.getIsBase() == true) {
                ejbFacade.setNewBases();
            } else {
                selected.setIsNow(true);
            }
            if (selected.getIsBase() == false && !JsfUtil.isValidationFailed()) {
                ejbFacade.setNewNows();
            }
            persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle8").getString("PeriodCreated"));

            if (!JsfUtil.isValidationFailed()) {
                items = null;    // Invalidate list of items to trigger re-query.
            }
        }
    }

    public void update() {
        if (selected.getIsBase() == true) {
            ejbFacade.setNewBases();
        }
        if (selected.getIsNow() == true) {
            ejbFacade.setNewNows();
        }
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle8").getString("PeriodUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle8").getString("PeriodDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Period> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle8").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle8").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Period getPeriod(java.lang.Integer id) {
        return getFacade().find(id);
    }

    public List<Period> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Period> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Period.class)
    public static class PeriodControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            PeriodController controller = (PeriodController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "periodController");
            return controller.getPeriod(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Period) {
                Period o = (Period) object;
                return getStringKey(o.getId());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Period.class.getName()});
                return null;
            }
        }

    }

}

web/SuperAdmin/period/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="PeriodCreateDlg" widgetVar="PeriodCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle8.CreatePeriodTitle}">
            <h:form id="PeriodCreateForm">
                <h:outputScript>
                    $(function(){
                      $("#PeriodCreateForm\\:startDate , #PeriodCreateForm\\:endDate").persianDatepicker();
                    });
                </h:outputScript>
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{periodController.selected != null}">
                        <p:outputLabel value="#{bundle8.CreatePeriodLabel_price}" for="price" />
                        <p:inputText id="price" value="#{periodController.selected.price}" title="#{bundle8.CreatePeriodTitle_price}" required="true" requiredMessage="#{bundle8.CreatePeriodRequiredMessage_price}"/>
                        <p:outputLabel value="#{bundle8.CreatePeriodLabel_startDate}" for="startDate" />
                        <p:inputText id="startDate" value="#{periodController.selected.startDate}" title="#{bundle8.EditPeriodTitle_startDate}" required="true" requiredMessage="#{bundle8.EditPeriodRequiredMessage_startDate}" >
                            <f:converter converterId="persian_date"/>
                        </p:inputText>
                        <p:outputLabel value="#{bundle8.CreatePeriodLabel_endDate}" for="endDate" />
                        <p:inputText id="endDate" value="#{periodController.selected.endDate}" title="#{bundle8.EditPeriodTitle_endDate}" required="true" requiredMessage="#{bundle8.EditPeriodRequiredMessage_endDate}" >
                            <f:converter converterId="persian_date"/>
                        </p:inputText>
                        <p:outputLabel value="#{bundle8.CreatePeriodLabel_isBase}" for="isBase" />
                        <p:selectBooleanCheckbox id="isBase" value="#{periodController.selected.isBase}" required="true" requiredMessage="#{bundle8.EditPeriodRequiredMessage_isBase}"/>
                        <p:outputLabel value="#{bundle8.CreatePeriodLabel_describtion}" for="describtion" />
                        <p:inputTextarea id="describtion" value="#{periodController.selected.describtion}" title="#{bundle8.CreatePeriodTitle_describtion}" />
                        <p:outputLabel value="تعداد کل جدید" for="CountNew" />
                        <p:inputNumber value="#{periodController.newCount}" id="CountNew" />
                    </p:panelGrid>
                    <p:commandButton actionListener="#{periodController.create}" value="#{bundle8.Save}" update="display,:PeriodListForm:datalist,:growl,:NotEqualDlg" oncomplete="handleSubmit(args,'PeriodCreateDialog');PF('NotEqualDlg').show();"/>
                    <p:commandButton type="button" value="#{bundle8.Cancel}" onclick="PF('PeriodCreateDialog').hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>
        <p:dialog id="NotEqualDlg" widgetVar="NotEqualDlg" modal="true" >
            <p:panel>
                <h:form id="NotEqualForm">
                    <p:panelGrid columns="2">
                    <p:outputLabel value="مقدار باقی مانده در افزایش سهام" for="ValueNotEqul" />
                    <p:inputText disabled="true" style="color: #000" id="ValueNotEqul" value="#{periodController.notEquals}" />
                    <p:outputLabel for="addcount" value="تعدادی که اضافه میکنید" />
                    <p:inputText value="#{periodController.addSaham}" id="addcount" />
                    <p:outputLabel for="user" value="کاربری که باقی مانده را به آن افزایش می دهید" />
                    <p:selectOneMenu id="user" filter="true" value="#{periodController.user}" >
                        <f:selectItems value="#{usersController.items}" var="item" 
                                       itemValue="#{item}" 
                                       itemLabel="#{item.name} #{item.familyMfrs}"/>
                    </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton value="ثبت اطلاعات" actionListener="#{periodController.addSahamToUser()}" update=":PeriodListForm:datalist,:growl,NotEqualForm"
                                     />
                </h:form>
            </p:panel>
        </p:dialog>

    </ui:composition>
</html>

web/SuperAdmin/period/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="PeriodEditDlg" widgetVar="PeriodEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle8.EditPeriodTitle}">
            <h:form id="PeriodEditForm">
                <h:panelGroup id="display">
                    <h:outputScript>
                    $(function(){
                      $("#PeriodEditForm\\:startDate , #PeriodEditForm\\:endDate").persianDatepicker();
                    });
                </h:outputScript>
                    <p:panelGrid columns="2" rendered="#{periodController.selected != null}">
                        <p:outputLabel value="#{bundle8.EditPeriodLabel_price}" for="price" />
                        <p:inputText id="price" value="#{periodController.selected.price}" title="#{bundle8.EditPeriodTitle_price}" required="true" requiredMessage="#{bundle8.EditPeriodRequiredMessage_price}"/>
                        <p:outputLabel value="#{bundle8.EditPeriodLabel_startDate}" for="startDate" />
                        <p:inputText id="startDate" value="#{periodController.selected.startDate}" title="#{bundle8.EditPeriodTitle_startDate}" required="true" requiredMessage="#{bundle8.EditPeriodRequiredMessage_startDate}" >
                            <f:converter converterId="persian_date"/>
                        </p:inputText>
                        <p:outputLabel value="#{bundle8.EditPeriodLabel_endDate}" for="endDate" />
                        <p:inputText id="endDate" value="#{periodController.selected.endDate}" title="#{bundle8.EditPeriodTitle_endDate}" required="true" requiredMessage="#{bundle8.EditPeriodRequiredMessage_endDate}" >
                            <f:converter converterId="persian_date"/>
                        </p:inputText>
                        <p:outputLabel value="#{bundle8.EditPeriodLabel_isBase}" for="isBase" />
                        <p:selectBooleanCheckbox onchange="#{periodController.selected.setIsNow(!periodController.selected.getIsBase())}" id="isBase" value="#{periodController.selected.isBase}" >
                            <f:ajax render="PeriodEditForm" execute="isBase"/>
                        </p:selectBooleanCheckbox>
                        <p:outputLabel value="#{bundle8.EditPeriodLabel_isNow}" for="isNow" />
                        <p:selectBooleanCheckbox id="isNow" onblur="#{periodController.selected.setIsBase(false)}" value="#{periodController.selected.isNow}" >
                            <f:ajax render="PeriodEditForm" execute="isNow"/>
                        </p:selectBooleanCheckbox>
                        <p:outputLabel value="#{bundle8.EditPeriodLabel_describtion}" for="describtion" />
                        <p:inputText id="describtion" value="#{periodController.selected.describtion}" title="#{bundle8.EditPeriodTitle_describtion}" />
                    </p:panelGrid>
                    <p:commandButton actionListener="#{periodController.update}" value="#{bundle8.Save}" update="display,:PeriodListForm:datalist,:growl" oncomplete="handleSubmit(args, 'PeriodEditDialog');"/>
                    <p:commandButton type="button" value="#{bundle8.Cancel}" onclick="PF('PeriodEditDialog').hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/SuperAdmin/period/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

    <ui:composition template="/SuperAdmin/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle8.ListPeriodTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body" >
            <c:if test="#{loginController.checkLogin('SuperAdmin')}">
                <h:form id="PeriodListForm">
                    <p:panel header="#{bundle8.ListPeriodTitle}">
                        <p:dataTable id="datalist" value="#{periodController.items}" var="item"
                                     selectionMode="single" selection="#{periodController.selected}"
                                     paginator="true"
                                     rowKey="#{item.id}"
                                     rows="10"
                                     rowsPerPageTemplate="10,20,30,40,50"
                                     >

                            <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                            <p:ajax event="rowDblselect" update=":PeriodViewForm" onsuccess="PF('PeriodViewDialog').show()"  />
                            <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                            <p:column>
                                <f:facet name="header">
                                    <h:outputText value="#{bundle8.ListPeriodTitle_id}"/>
                                </f:facet>
                                <h:outputText value="#{item.id}"/>
                            </p:column>
                            <p:column>
                                <f:facet name="header">
                                    <h:outputText value="#{bundle8.ListPeriodTitle_price}"/>
                                </f:facet>
                                <h:outputText value="#{item.price}"/>
                            </p:column>
                            <p:column>
                                <f:facet name="header">
                                    <h:outputText value="#{bundle8.ListPeriodTitle_startDate}"/>
                                </f:facet>
                                <h:outputText value="#{item.startDate}">
                                    <f:converter converterId="persian_date" />
                                </h:outputText>
                            </p:column>
                            <p:column>
                                <f:facet name="header">
                                    <h:outputText value="#{bundle8.ListPeriodTitle_endDate}"/>
                                </f:facet>
                                <h:outputText value="#{item.endDate}">
                                    <f:converter converterId="persian_date" />
                                </h:outputText>
                            </p:column>
                            <p:column>
                                <f:facet name="header">
                                    <h:outputText value="#{bundle8.ListPeriodTitle_isBase}"/>
                                </f:facet>
                                <p:selectBooleanCheckbox value="#{item.isBase}" disabled="true"/>
                            </p:column>
                            <p:column>
                                <f:facet name="header">
                                    <h:outputText value="#{bundle8.ListPeriodTitle_isNow}"/>
                                </f:facet>
                                <p:selectBooleanCheckbox value="#{item.isNow}" disabled="true"/>
                            </p:column>
                            <p:column sortBy="#{item.oldCount}" filterBy="#{item.oldCount}">
                                <f:facet name="header">
                                    <h:outputText value="مقدار سهام قبلی" />
                                </f:facet>
                                <h:outputText value="#{item.oldCount}" />
                            </p:column>
                            <p:column sortBy="#{item.newCount}" filterBy="#{item.newCount}">
                                <f:facet name="header">
                                    <h:outputText value="مقدار سهام جدید" />
                                </f:facet>
                                <h:outputText value="#{item.newCount}" />
                            </p:column>
                            <p:column sortBy="#{item.notEquale}" filterBy="#{ item.notEquale}">
                                <f:facet name="header">
                                    <h:outputText value="مقدار سهام باقی مانده" />
                                </f:facet>
                                <h:outputText value="#{item.notEquale}" />
                            </p:column>
                            <p:column >
                                <f:facet name="header">
                                    <h:outputText value=" افزایش به ازای هر سهم"/>
                                </f:facet>
                                <h:outputText value="#{item.sharesOffer}" />
                            </p:column>
                            <p:column>
                                <f:facet name="header">
                                    <h:outputText value="#{bundle8.ListPeriodTitle_describtion}"/>
                                </f:facet>
                                <h:outputText value="#{item.describtion}"/>
                            </p:column>
                            <p:column>
                                <f:facet name="header">
                                    <h:outputText value="#{bundle8.ListPeriodTitle_createdAt}"/>
                                </f:facet>
                                <h:outputText value="#{item.createdAt}">
                                    <f:converter converterId="persian_date" />
                                </h:outputText>
                            </p:column>
                            <p:column>
                                <f:facet name="header">
                                    <h:outputText value="#{bundle8.ListPeriodTitle_updatedAt}"/>
                                </f:facet>
                                <h:outputText value="#{item.updatedAt}">
                                    <f:converter converterId="persian_date" />
                                </h:outputText>
                            </p:column>
                            <f:facet name="footer">
                                <c:if test="#{periodController.checkNotEquale()}">
                                    <p:commandButton  update=":growl,:NotEqualDlg" oncomplete="PF('NotEqualDlg').show();" value="تخصیص سهام باقی مانده" />
                                </c:if>
                                <p:commandButton id="createButton" disabled="#{periodController.checkNotEquale() ? true : false}"  title="#{periodController.checkNotEquale() ? 'تعدادی سهام بلاتکلیف موجود می باشد' : 'افزودن'}" icon="ui-icon-plus"   value="#{bundle8.Create}" actionListener="#{periodController.prepareCreate}" update=":PeriodCreateForm" oncomplete="PF('PeriodCreateDialog').show()"/>
                                <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle8.View}" update=":PeriodViewForm" oncomplete="PF('PeriodViewDialog').show()" disabled="#{empty periodController.selected}"/>
                                <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle8.Edit}" update=":PeriodEditForm" oncomplete="PF('PeriodEditDialog').show()" disabled="#{empty periodController.selected}"/>
                                <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle8.Delete}" actionListener="#{periodController.destroy}" update=":growl,datalist" disabled="#{empty periodController.selected}">
                                  <p:confirm message="آیا از حذف اطمینان دارید" />
                                </p:commandButton>
                            </f:facet>
                        </p:dataTable>
                    </p:panel>
                </h:form>

                <ui:include src="Create.xhtml"/>
                <ui:include src="Edit.xhtml"/>
                <ui:include src="View.xhtml"/>
            </c:if>
        </ui:define>
    </ui:composition>

</html>

web/SuperAdmin/period/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="PeriodViewDlg" widgetVar="PeriodViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle8.ViewPeriodTitle}">
            <h:form id="PeriodViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{periodController.selected != null}">
                        <h:outputText value="#{bundle8.ViewPeriodLabel_id}"/>
                        <h:outputText value="#{periodController.selected.id}" title="#{bundle8.ViewPeriodTitle_id}"/>
                        <h:outputText value="#{bundle8.ViewPeriodLabel_price}"/>
                        <h:outputText value="#{periodController.selected.price}" title="#{bundle8.ViewPeriodTitle_price}"/>
                        <h:outputText value="#{bundle8.ViewPeriodLabel_startDate}"/>
                        <h:outputText value="#{periodController.selected.startDate}" title="#{bundle8.ViewPeriodTitle_startDate}">
                            <f:converter converterId="persian_date" />
                        </h:outputText>
                        <h:outputText value="#{bundle8.ViewPeriodLabel_endDate}"/>
                        <h:outputText value="#{periodController.selected.endDate}" title="#{bundle8.ViewPeriodTitle_endDate}">
                            <f:converter converterId="persian_date" />
                        </h:outputText>
                        <h:outputText value="#{bundle8.ViewPeriodLabel_isBase}"/>
                        <p:selectBooleanCheckbox value="#{periodController.selected.isBase}" disabled="true"/>
                        <h:outputText value="#{bundle8.ViewPeriodLabel_isNow}"/>
                        <p:selectBooleanCheckbox value="#{periodController.selected.isNow}" disabled="true"/>
                        <h:outputText value="#{bundle8.ViewPeriodLabel_describtion}"/>
                        <h:outputText value="#{periodController.selected.describtion}" title="#{bundle8.ViewPeriodTitle_describtion}"/>
                        <h:outputText value="#{bundle8.ViewPeriodLabel_createdAt}"/>
                        <h:outputText value="#{periodController.selected.createdAt}" title="#{bundle8.ViewPeriodTitle_createdAt}">
                            <f:converter converterId="persian_date" />
                        </h:outputText>
                        <h:outputText value="#{bundle8.ViewPeriodLabel_updatedAt}"/>
                        <h:outputText value="#{periodController.selected.updatedAt}" title="#{bundle8.ViewPeriodTitle_updatedAt}">
                            <f:converter converterId="persian_date" />
                        </h:outputText>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle8.Close}" onclick="PF('PeriodViewDialog').hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>